sonar.projectKey=AnouarMohamed_ai-task-manager-laravel
sonar.organization=anouarmohamed
sonar.projectName=AI Task Manager Laravel
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=app,routes,resources
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**
